#!/usr/bin/env python3
"""Run the agent and write a transcript.

    python run.py --demo                     # no API key needed, checks the wiring
    python run.py --live -m "your message"   # the real Messages API
    python run.py --live --scenario happy    # one of the canned customer messages

Your two submitted transcripts should come from --live. The transcripts land in
transcripts/ as markdown.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

from agent.loop import run_agent
from agent.model import LiveModel, ScriptedModel
from agent.session import Session
from agent.transcript import TranscriptRecorder

TRANSCRIPT_DIR = pathlib.Path(__file__).parent / "transcripts"

# The two customer messages your submitted transcripts should be built from.
SCENARIOS = {
    "happy": (
        "Hi - Alice Nguyen here, alice@example.com. The ceramic pour-over kettle from "
        "ORD-123 arrived with a hairline crack running down the spout, so it leaks when "
        "I use it. I'd like my money back please."
    ),
    "escalation": (
        "Bob Okafor, bob@example.com. Two things and I'd rather not have to chase either "
        "of them again. First, the professional stand mixer on ORD-456 turned up with the "
        "housing crushed on one side - that was $899 and I want the whole lot back. "
        "Second, the cast iron skillet on ORD-321 has a chip in the enamel, so I'd like "
        "that one refunded too. Where do I stand?"
    ),
    "human": (
        "I don't want to go through this with a bot. Put me through to an actual person."
    ),
}

# A tiny scripted run that only touches the two handlers already implemented, so a
# fresh clone does something visible before you have written any code.
DEMO_SCRIPT = [
    {
        "stop_reason": "tool_use",
        "content": [
            {"type": "text", "text": "Let me pull up your account first."},
            {
                "type": "tool_use",
                "id": "toolu_demo1",
                "name": "get_customer",
                "input": {"email": "alice@example.com"},
            },
        ],
    },
    {
        "stop_reason": "tool_use",
        "content": [
            {
                "type": "tool_use",
                "id": "toolu_demo2",
                "name": "lookup_order",
                "input": {"order_id": "ORD-123"},
            }
        ],
    },
    {
        "stop_reason": "end_turn",
        "content": [
            {
                "type": "text",
                "text": (
                    "Wiring check passed. get_customer and lookup_order are working, the "
                    "identity gate allowed both, and the loop terminated on end_turn. "
                    "Everything else is yours to build."
                ),
            }
        ],
    },
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--live", action="store_true", help="call the real Messages API")
    parser.add_argument("--demo", action="store_true", help="scripted wiring check, no API key")
    parser.add_argument("--scenario", choices=list(SCENARIOS), help="a canned customer message")
    parser.add_argument("-m", "--message", help="your own customer message")
    parser.add_argument("--out", help="transcript filename, e.g. transcripts/01-happy-path.md")
    args = parser.parse_args()

    if not args.live and not args.demo:
        parser.error("pass --demo for the wiring check, or --live to call the API")

    if args.demo:
        model = ScriptedModel(DEMO_SCRIPT)
        message = SCENARIOS["happy"]
        label = "demo"
    else:
        model = LiveModel()
        message = args.message or SCENARIOS.get(args.scenario or "happy")
        label = args.scenario or "live"

    session = Session()
    recorder = TranscriptRecorder(
        title=f"Transcript - {label}",
        subtitle="Generated by run.py.",
        mode="live Messages API (claude-opus-5)" if args.live else "scripted (offline)",
    )

    result = run_agent(
        user_message=message, model=model, session=session, recorder=recorder
    )

    out = pathlib.Path(args.out) if args.out else TRANSCRIPT_DIR / f"{label}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(recorder.render(result, session), encoding="utf-8")

    print(
        f"[{label}] {result.turns} turns | "
        f"verified={session.verified_customer_id or 'no'} | "
        f"refunds={session.refunded_by_order or '{}'} | "
        f"tickets={[t['ticket_id'] for t in session.tickets] or '[]'} | "
        f"wrote {out}"
    )
    print("\n--- final reply ---\n" + (result.final_text or "(no text)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
